
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#undef REST_MAX_CHUNK_SIZE
#define REST_MAX_CHUNK_SIZE 64

#undef COAP_MAX_OPEN_TRANSACTIONS
#define COAP_MAX_OPEN_TRANSACTIONS 4

#undef NBR_TABLE_CONF_MAX_NEIGHBORS
#define NBR_TABLE_CONF_MAX_NEIGHBORS 10

#undef UIP_CONF_MAX_ROUTES
#define UIP_CONF_MAX_ROUTES 10

#undef UIP_CONF_BUFFER_SIZE
#define UIP_CONF_BUFFER_SIZE 240

#define LOG_LEVEL_APP LOG_LEVEL_DBG

#endif /* PROJECT_CONF_H_ */



